name: 构建并推送gitbook容器镜像

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 登陆GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: 构建并推送镜像
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/gitbook
          docker build -t $IMAGE_NAME:latest ./node/gitbook
          docker push $IMAGE_NAME:latest